# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-16 20:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('serialnumber', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:  '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('current_location', models.CharField(blank=True, max_length=200, null=True)),
                ('nearest_city', models.CharField(blank=True, max_length=200, null=True)),
                ('ug_course', models.CharField(blank=True, max_length=200, null=True)),
                ('ug_institute_name', models.CharField(blank=True, max_length=300, null=True)),
                ('ug_tier_one', models.BooleanField(default=False)),
                ('ug_passing_year', models.IntegerField(blank=True, null=True)),
                ('pg_course', models.CharField(blank=True, max_length=100, null=True)),
                ('pg_institute_name', models.CharField(blank=True, max_length=300, null=True)),
                ('pg_tier_one', models.BooleanField(default=False)),
                ('pg_passing_year', models.IntegerField(blank=True, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=200, null=True)),
                ('resume', models.BooleanField(default=False)),
                ('work_experience', models.FloatField(blank=True, null=True)),
                ('analytics_experience', models.FloatField(blank=True, null=True)),
                ('current_employer', models.CharField(blank=True, max_length=200, null=True)),
                ('ctc', models.FloatField(blank=True, null=True)),
                ('current_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('any_other_course', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
